### ISSUE TITLE
If links contains word in another language will fail

### ISSUE THREAD

**Issue by JackTanHiyake** [ARTEZON/telegraph-image-downloader#1]
Hi, the is a great software that able to download all the pictures from telegraph link.
Unfortunately if I provide a link that contains word in another language like chinese and it will fail
Any workarounds?
Thank you very much!!
![image](https://user-images.githubusercontent.com/117102672/205668688-69146f32-5e90-47c3-a8a9-3a9364622406.png)
the word in chinese cannot be pasted properly (may be the issue)

**Comment by Artezon** [comment]
Hello! I was able to reproduce the bug and now I'm fixing the issue.

**Comment by Artezon** [comment]
This issue is fixed in the new version. [Try it out!](https://github.com/ARTEZON/telegraph-image-downloader/releases/tag/v1.2.2)

**Comment by JackTanHiyake** [comment]
Thanks a lot!!
