### ISSUE TITLE
Image link to googleusercontent.com not downloaded

### ISSUE THREAD

**Issue by zero0n3** [ARTEZON/telegraph-image-downloader#3]
Hello
There is a link on telegra.ph with images linked to lh3.googleusercontent.com google storage and your script went in error when try to download image. But if i copy/paste the link into browser it show the image perfectly.

Here you are one of that links not downloaded:
`https://lh5.googleusercontent.com/6ZVrJWQlQ5JieOpMfPtGNPER0o17NOyyNfwth7U9rge6GT3zdo6iWzzbqw0eqISAfPF6Cyj093Pz_Y_qnTogtRueHmHG85H_YAlJxz_pM-Ifnoh4JZuIJ5xxJzqJbh7Vk0RrhntD`

Thanks

**Comment by Artezon** [comment]
I found a workaround and it will work in a new version. It will come out when issue #2 is closed.

Waiting for your answer there :)

**Comment by Artezon** [comment]
Fixed in [version 1.2.3](https://github.com/ARTEZON/telegraph-image-downloader/releases/tag/v1.2.3)
