### ISSUE TITLE
Fixes for 2 bugs

### ISSUE THREAD

**Issue by XCanG** [ARTEZON/telegraph-image-downloader#4]
Hello, my friend faced today a bug in a script and asked for fix, I helped him to solve it and come back to this repo to report.

Bug that he encounter related to wrongly detected encoding of html, he got crash when he tried to get title with regex, see [this line](https://github.com/ARTEZON/telegraph-image-downloader/blob/main/TGIDownloader_EN.py#L324).

For that fix I changed line to check regex match first and exit from program if it = `None`
Just add a check before calling `.group` because `re.search` result either `re.Match` or `None`.

Secondly I diminished bug that related to encoding isssue, for that I use https://pypi.org/project/charset-normalizer/ library.
I imported `from charset_normalizer import from_bytes` and changed code in [line 132](https://github.com/ARTEZON/telegraph-image-downloader/blob/main/TGIDownloader_EN.py#L132) into:
```py
                encoding_fix = str(from_bytes(requests.get(url).content).best())
                html = list(str(bs(encoding_fix, features='html.parser')).split('\n'))
```
But it's not ideal code, since in very rare case `.best()` may produce `None` too if encoding is too weird, but that occurrence is < 0.5%. While charset-normalizer is best python lib for encoding guessing it also can fail sometimes. At least I encounter it for myself when tried to detect file names within eastern zip archives.

**Comment by Artezon** [comment]
Hello, thanks for the info.

I added a fallback condition, thus when `re.search` can't find title or description it won't throw an error anymore.

However, I have never experienced your encoding issue with lots of various languages. As far as I know, all web pages on Telegraph and Teletype are encoded in UTF-8 and python `requests` library can detect this itself. That's why I consider unnecessary adding one more dependency just for checking it. I may be wrong, hence, it would be nice if you could provide a link to a page which is encoded differently and can't be read by my program, so I will have better understanding of the issue.

Kind regards,
ARTEZON

**Comment by XCanG** [comment]
Well, I'm sure for most cases it might be UTF-8, but it's not always the case, that was the link that have issue with exact case:
```py
>>> import requests
>>> r = requests.get("https://teletype.in/@lnmanga/aOlhWEEjp10")
>>> r
<Response [200]>
>>> r.encoding
'ISO-8859-1'
```
So, taking `r.text` result in gibberish characters, that's why I take bytes (`.content`) instead and detect encoding with `charset-normalizer`.

**Comment by Artezon** [comment]
Thanks for the example. I tried a few things and I got it working even without `charset-normalizer`.

In this case I got properly decoded Russian characters after I changed `r.text` to `r.content.decode()`:
```
>>> import requests, re
>>> r = requests.get("https://teletype.in/@lnmanga/aOlhWEEjp10")
>>> html = r.content.decode()
>>> regex = re.search("<title>(.*) — Teletype</title>", html)
>>> print(regex.group(1))
Существование - 27 глава
```

After making corresponding changes to my program, it downloaded images without any problems. I will close this issue after pushing these changes to the repository. Please let me know If you consider the issue still unsolved.
